<a href="https://colab.research.google.com/github/justynakosinska/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Podstawy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__annotations__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

####1D Array jednowymiarowa

In [6]:
x=np.array([1,2,3])

In [7]:
print(x)

[1 2 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(3,)

In [11]:
x.size

3

In [12]:
x.dtype

dtype('int64')

In [13]:
x=np.array([1.2,2.3,1.4])
print(x)

[1.2 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

####2D Array-dwuwymiarowa

In [15]:
x=np.array([[1,2],[-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [16]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [20]:
x=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(x)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [21]:
x.shape

(3, 3)

####3D Array-do przechowywania obrazów

In [22]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

###Typy danych

In [25]:
a=np.array([1,2,3])
a.dtype

dtype('int64')

In [26]:
a=np.array([1.1,2.4,3.2])
a.dtype

dtype('float64')

In [27]:
a=np.array([1,2,3],dtype='float')
a.dtype

dtype('float64')

In [28]:
print(a)

[1. 2. 3.]


In [29]:
a=np.array([1,2,3],dtype='complex')
a.dtype

dtype('complex128')

In [30]:
print(a)

[1.+0.j 2.+0.j 3.+0.j]


###Tworzenie tablic

In [32]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [43]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [44]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [45]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###Podstawowe operacje na tablicach

In [49]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [50]:
A + B

array([6, 0, 7, 4])

In [51]:
A - B

array([0, 2, 1, 0])

In [52]:
A * B

array([ 9, -1, 12,  4])

In [53]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [54]:
np.add(A, B)

array([6, 0, 7, 4])

In [55]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [56]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [57]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [58]:
A + 3

array([6, 4, 7, 5])

In [59]:
2 * A

array([6, 2, 8, 4])

In [60]:
A + 3*B

array([12, -2, 13,  8])

In [61]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [62]:
X * Y

array([[6, 0],
       [2, 0]])

In [63]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [64]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [65]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [66]:
X @ Y

array([[  3,   6],
       [-12,   0]])

###Generowanie liczb pseudolosowych